### ISSUE TITLE
Support M106 and M107

### ISSUE THREAD

**Issue by crysxd** [z4gunn/OctoPrint-GpioFanController#1]
It would be amazing if you can add support for M106 M107 so the controlled fan can be used as a part cooling fan. Use case: My mainboard is broken and always send full speed to the part cooling fan.

There is a callback function a plugin can use to execute code whenever a specific Gcode is sent :) FanSpeedMirror is already doing something very similar: https://github.com/b-morgan/OctoPrint-FanSpeedMirror/blob/master/octoprint_FanSpeedMirror/__init__.py

Thank you very much for considering this feature!

**Comment by z4gunn** [comment]
> It would be amazing if you can add support for M106 M107 so the controlled fan can be used as a part cooling fan. Use case: My mainboard is broken and always send full speed to the part cooling fan.
> 
> There is a callback function a plugin can use to execute code whenever a specific Gcode is sent :) FanSpeedMirror is already doing something very similar: https://github.com/b-morgan/OctoPrint-FanSpeedMirror/blob/master/octoprint_FanSpeedMirror/__init__.py
> 
> Thank you very much for considering this feature!

Thanks for the feedback and agree that would be very useful.  I am planning on adding GCODE command hooks as the next feature.

**Comment by OldCurmudgeon3DP** [comment]
In my case (pun), my board fan, even being a noctua, is audible from several feet and runs all the time. I've been toying with the idea of remixing the case to use my OEM 4010 (sitting in a bin) or a 5015. This plugin would benefit that mod if it allowed gcode or event-based control of the fan.
There may be other options for me since I'm running Klipper firmware, but thought I'd chime in w/ an idea in case it was useful to others.

**Comment by z4gunn** [comment]
M106 and M107 GCODE command hooks have been added to v0.2.0

**Comment by crysxd** [comment]
Amazing! Will give it a shot and report back
